# Generated by Django 4.2.10 on 2025-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
