# Generated by Django 4.2.10 on 2025-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_meal_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cook_time',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='prep_time',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
