# Generated by Django 4.2.10 on 2025-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_meal_cook_time_meal_prep_time_meal_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
